### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by semiprime** [comment]
Many thanks! Checking the files now.

**Comment by Vistaus** [comment]
Thanks! I resolved everything. 🙂

**Comment by semiprime** [comment]
Thanks! Very grateful for this.

On merging, I noticed that there was no translator credit in the application's "About" dialog.

I'm now adding one, and obviously would like to credit you. Should I just put "Heimen Stoffels"? (I can put something else or omit the credit if you wish - just let me know.)

**Comment by Vistaus** [comment]
Always happy to help out! 🙂

Yes, Heimen Stoffels is fine. You can additionally add a link to my GitHub profile if that's something you think fits/is to your liking, but if not, then just my name is fine.

**Pull request merged**
